# TODO replace name with name of ebook: 101: Intro to Web, 411: Front-Ends with React...etc
site_name: JS311 - Node Servers + SQL Databases

# TODO inside `ebook-folder/`
# TODO run `git clone https://github.com/squidfunk/mkdocs-material.git`
# TODO run `pip install -r requirements.txt` (see inside mkdocs-material/)
# TODO run `mkdocs build` to build the static files into "/site"
# TODO run `mkdocs serve` to serve those files to http://127.0.0.1:8000
# TODO replace all CAPITALIZED words with appropriate titles
# ! Use the files in workspace/resources to quickly generate class and lesson templates, see `cp ...` script at bottom of each file
# ! Use the folder workspace/developmentDocumentation to record thoughts and future improvements

# defines where the markdown to build from
# docs_dir: 'test-node-book'

# defines where to put the generated static files
# site_dir: 'docs'

# "pages" has been deprecated
# use this to create the nav bar on the left-side of the window view
# TODO replace all CAPITALIZED words with appropriate titles

nav:
    - Home: 'index.md'
    - 'Module One: Express Servers':
      - 'Pre-Class 1 Lessons': 
        - Prepare Your Machine: module-1/prepareYourMachine.md
        - Code Sandboxes: module-1/codeSandboxes.md
        - How to Succeed: module-1/succeedInThisCourse.md
        - Working in Node: module-1/whatIsNodeJS.md
        - Intro to APIs: module-1/REST-HTTP-APIs.md
        - Node & NPM: module-1/nodeRecap.md
        - Pre-Class Checklist: module-1/preClassOneChecklist.md
        - Class 1 Node, NPM, & Postman: module-1/class-1.md
      - 'Pre-Class 2 Lesson': 
        # TODO - Develop TITLE: module-1/developSeries-.md
        - Axios + Status Codes: module-1/axios-HTTPstatusCodes.md
        - Class 2 Axios Practice: module-1/class-2.md
      - 'Pre-Class 3 Lesson':
        # TODO - Develop TITLE: module-1/developSeries-.md
        - Intro To Express: module-1/introToExpress.md
        - Class 3 First Server: module-1/class-3.md
      - 'Pre-Class 4 Lesson':
        # TODO - Develop TITLE: module-1/developSeries-.md
        - Routers: module-1/expressRouters.md
        - Controllers: module-1/expressControllers.md
        - Static Files: module-1/expressStaticFiles.md
        - Class 4 Serving Static Files: module-1/class-4.md
    - 'Module Two: MySQL Database': 
      - 'Pre-Class 5 Lessons': 
        - Database Intro: module-2/databaseIntro.md
        - MySQL Workbench: module-2/mySql-WorkbenchSetup.md
        - DB on GCP: module-2/setupDatabaseOnGCP.md
        - SELECT Statements: module-2/writingSELECTstatements.md
        # https://studio.zollege.com/course/course-v1:ACA+JS311+08172020_JS311_C6?show=block-v1%3AACA%2BJS311%2B08172020_JS311_C6%2Btype%40sequential%2Bblock%403f8633c1642543358d1afd7a9f1c324f
        - Class 5 SELECT: module-2/class-5.md
        # - 'Pre-Class 6 Lesson': 
        # - 'Pre-Class 7 Lesson': 
        # - 'Pre-Class 8 Lesson': 
      # - 'Module Three: TITLE': 
        # - 'Pre-Class 9 Lesson': 
        # - 'Pre-Class 10 Lesson': 
        # - 'Pre-Class 11 Lesson': 
        # - 'Pre-Class 12 Lesson': 
      # - 'Module Four: TITLE':
        # - 'Pre-Class 13 Lesson': 
        # - 'Pre-Class 14 Lesson': 
        # - 'Pre-Class 15 Lesson': 
        # - 'Pre-Class 16 Lesson':  
    - 'Additional Resources':
      - Interview Training: additionalResources/interviewChallenges.md
      - Student Presentations: additionalResources/studentPresentations.md
      - Develop Series Collection: additionalResources/developSeries.md
      - 'Questions for Discussion Collections':
        - Day 1 QFD: additionalResources/questionsForDiscussion/qfd-class-1.md
        - Day 2 QFD: additionalResources/questionsForDiscussion/qfd-class-2.md
        - Day 3 QFD: additionalResources/questionsForDiscussion/qfd-class-3.md
        - Day 4 QFD: additionalResources/questionsForDiscussion/qfd-class-4.md
        - Day 5 QFD: additionalResources/questionsForDiscussion/qfd-class-5.md
      - Blog Prompts: additionalResources/blogPrompts.md
      - Keyboard Shortcuts: additionalResources/keyboardShortcuts.md
      - Git & CLI Commands: additionalResources/gitCommands.md
      - Learn Your CLI: additionalResources/learnYourCLI.md
      - Graduation Prerequisites: additionalResources/graduationPrerequisites.md
      - Presentation Qualifications: additionalResources/presentationsQualifications.md
      # - 'Bonus Materials':


# defines the styles, usually just a single name but `custom_dir` overrides this behavior
theme:
  name: material
  # was null
  palette:
    scheme: slate
    primary: black
    accent: deep orange
    # Defines the logo in the top-left, file must be in the /doc directory
  logo: CE_WhiteBlue_Icon.png
  
  # ? Not rendering as expected??
  extra:
    copyright: Copyright &copy; 2013 - 2021 Austin Coding Academy
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/AustinCodingAcademy
      - icon: fontawesome/brands/medium
        link: https://medium.com/@austincoding
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/school/austincodingacademy/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/austincodingacademy
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/austincoding
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/AustinCodingAcademy/


  
  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
  - def_list
  - pymdownx.tabbed


 

# Can add icons throughout the ebook https://materialdesignicons.com/
#  - pymdownx.inlinehilite
  # - pymdownx.keys